[deps]
DiagonalArrays = "74fd4be6-21e2-4f6f-823a-4360d37c7a77"
SparseArraysBase = "0d5efcca-f356-4864-8770-e1ed8d78f208"

[sources]
SparseArraysBase = {url = "https://github.com/ITensor/SparseArraysBase.jl"}
